spring.application.name=aksigorta_final

# server port change
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:~/aksigorta_final_db;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=sa

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OpenAPI / Swagger UI
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
